### ISSUE TITLE
Assignment3에 대한 문의 사항이 있습니다.

### ISSUE THREAD

**Issue by lybell-art** [wanted-pre-onboarding-fe/pre-assignment#1]
이메일과 비밀번호의 유효성 검사 중 "**로그인 시 이메일과 비밀번호가 등록되어 있는 것과 일치 여부 확인**"이라는 게 있는데, 등록된 이메일과 비밀번호 데이터는 과제 수행자가 임의적으로 설정해야 하는 건가요?

**Comment by bclef2525** [comment]
네 임의로 설정하시면 됩니다-! 해당 정보가 일치하지 않는다면 alert등을 띄워주면 더 좋을 것 같네요~

**Comment by bclef2525** [comment]
확인하시고 이슈를 닫아주시면 감사하겠습니다~ :)

**Comment by lybell-art** [comment]
감사합니다:)
