### ISSUE TITLE
Assginment 2 관련 문의사항입니다.

### ISSUE THREAD

**Issue by yeonjinkimm** [wanted-pre-onboarding-fe/pre-assignment#2]
노션에 있는 Assginment 2 참고 이미지는 GNB 부분만 참고하면 되는걸까요?
GNB 아래의 피드 형식은 Assginment 5 와 같게 만들면 되는지 궁금합니다 !

**Comment by bclef2525** [comment]
네 맞습니다..!! 전부 다 구현하실 필요는 없습니다!(assignment2 참고 이미지의 GNB외 다른 부분은 무시하셔도 됩니다)

**Comment by yeonjinkimm** [comment]
답변 감사합니다 ! :)
