### ISSUE TITLE
Plugin "react" was conflicted between ".eslintrc"

### ISSUE THREAD

**Issue by tjswo2292** [wanted-pre-onboarding-fe/pre-assignment#5]
제목과 같은 에러 메시지를 해결하기 위해
과제 폴더 내에 .eslintrc 에서 "root": true 를 추가 했는데 괜찮을까요?

**Comment by bclef2525** [comment]
혹시라도 문제 되는 부분이 있다면 추가 하고 진행 하셔도 괜찮습니다 :)
